// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxx6FKyg5gJiM7iNUKbc-tJmo_ScTfaeY',
    appId: '1:436678880838:web:ee700bd4860ee9e8a62447',
    messagingSenderId: '436678880838',
    projectId: 'prompt-5a926',
    authDomain: 'prompt-5a926.firebaseapp.com',
    storageBucket: 'prompt-5a926.firebasestorage.app',
    measurementId: 'G-7BQ5EV2W8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2dAOCTxsy4upPv8gDMCPZkZmyJl2L3Kk',
    appId: '1:436678880838:android:785f430b0bcaeab2a62447',
    messagingSenderId: '436678880838',
    projectId: 'prompt-5a926',
    storageBucket: 'prompt-5a926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEczYJ7Qhu78gxhKB6F9WAvHnB-knH7D8',
    appId: '1:436678880838:ios:8a7a9312668f01c7a62447',
    messagingSenderId: '436678880838',
    projectId: 'prompt-5a926',
    storageBucket: 'prompt-5a926.firebasestorage.app',
    iosClientId: '436678880838-icrm6lvp1iaqu3bdv67uioeinaap8r9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.promtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEczYJ7Qhu78gxhKB6F9WAvHnB-knH7D8',
    appId: '1:436678880838:ios:8a7a9312668f01c7a62447',
    messagingSenderId: '436678880838',
    projectId: 'prompt-5a926',
    storageBucket: 'prompt-5a926.firebasestorage.app',
    iosClientId: '436678880838-icrm6lvp1iaqu3bdv67uioeinaap8r9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.promtApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxx6FKyg5gJiM7iNUKbc-tJmo_ScTfaeY',
    appId: '1:436678880838:web:af6fbab1de7d5804a62447',
    messagingSenderId: '436678880838',
    projectId: 'prompt-5a926',
    authDomain: 'prompt-5a926.firebaseapp.com',
    storageBucket: 'prompt-5a926.firebasestorage.app',
    measurementId: 'G-HV9XQ4DLP3',
  );
}
