const appConfig = {
  categories: [
    {
      id: 'general',
      label: 'General',
      iconKey: 'sparkles',
      visualStyle: 'lavender',
      order: 0,
      enabled: true,
    },
    {
      id: 'coding',
      label: 'Coding',
      iconKey: 'code',
      visualStyle: 'mint',
      order: 1,
      enabled: true,
    },
    {
      id: 'writing',
      label: 'Writing',
      iconKey: 'edit',
      visualStyle: 'blush',
      order: 2,
      enabled: true,
    },
    {
      id: 'image-generation',
      label: 'Image',
      iconKey: 'image',
      visualStyle: 'lime',
      order: 3,
      enabled: true,
    },
    {
      id: 'business',
      label: 'Business',
      iconKey: 'briefcase',
      visualStyle: 'sky',
      order: 4,
      enabled: true,
    },
  ],
  tones: [
    {
      id: 'auto',
      label: 'Auto',
      iconKey: 'sparkles',
      premiumOnly: false,
      order: 0,
      promptPolicyKey: 'auto',
    },
    {
      id: 'professional',
      label: 'Professional',
      iconKey: 'briefcase',
      premiumOnly: true,
      order: 1,
      promptPolicyKey: 'professional',
    },
    {
      id: 'creative',
      label: 'Creative',
      iconKey: 'palette',
      premiumOnly: true,
      order: 2,
      promptPolicyKey: 'creative',
    },
    {
      id: 'casual',
      label: 'Casual',
      iconKey: 'chat',
      premiumOnly: true,
      order: 3,
      promptPolicyKey: 'casual',
    },
    {
      id: 'persuasive',
      label: 'Persuasive',
      iconKey: 'megaphone',
      premiumOnly: true,
      order: 4,
      promptPolicyKey: 'persuasive',
    },
    {
      id: 'technical',
      label: 'Technical',
      iconKey: 'settings',
      premiumOnly: true,
      order: 5,
      promptPolicyKey: 'technical',
    },
  ],
  templateCategories: [
    { id: 'general', label: 'General', iconKey: 'sparkles', order: 0 },
    { id: 'coding', label: 'Coding', iconKey: 'code', order: 1 },
    { id: 'writing', label: 'Writing', iconKey: 'edit', order: 2 },
    { id: 'image-generation', label: 'Image', iconKey: 'image', order: 3 },
    { id: 'business', label: 'Business', iconKey: 'briefcase', order: 4 },
  ],
  templates: [
    {
      id: 'general-explain',
      categoryId: 'general',
      title: 'Explain a concept',
      summary: 'Turn a rough idea into a clear explanation.',
      promptBody: 'Explain [concept] in simple terms with examples and useful context.',
      isQuick: true,
      enabled: true,
    },
    {
      id: 'coding-review',
      categoryId: 'coding',
      title: 'Code review',
      summary: 'Review code for bugs, clarity, and performance.',
      promptBody: 'Review this code and suggest fixes, improvements, and edge cases...',
      isQuick: true,
      enabled: true,
    },
    {
      id: 'writing-email',
      categoryId: 'writing',
      title: 'Professional email',
      summary: 'Write a polished email with a clear tone and ask.',
      promptBody: 'Write a professional email about...',
      isQuick: true,
      enabled: true,
    },
    {
      id: 'image-scene',
      categoryId: 'image-generation',
      title: 'Image prompt',
      summary: 'Describe style, camera, mood, and details clearly.',
      promptBody: 'Create a detailed image prompt for...',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'business-plan',
      categoryId: 'business',
      title: 'Business plan',
      summary: 'Outline a plan with goals, positioning, and next steps.',
      promptBody: 'Create a business plan for...',
      isQuick: false,
      enabled: true,
    },
  ],
  homeFeatures: [
    {
      id: 'refine',
      title: 'Refine your prompt',
      subtitle: 'Start with a rough thought and shape it into something clear.',
      iconKey: 'sparkles',
      imageAssetKey: 'orb',
      actionType: 'compose',
      visualSize: 'large',
    },
    {
      id: 'voice',
      title: 'Use your voice',
      subtitle: 'Say what you mean naturally and edit it after.',
      iconKey: 'mic',
      imageAssetKey: 'voice',
      actionType: 'voice',
      visualSize: 'medium',
    },
    {
      id: 'templates',
      title: 'Browse templates',
      subtitle: 'Use starting points that already work well.',
      iconKey: 'grid',
      imageAssetKey: 'template',
      actionType: 'templates',
      visualSize: 'medium',
    },
  ],
  visualAssets: [
    {
      id: 'home-orb',
      placement: 'home-hero',
      lightAssetUrl: '',
      darkAssetUrl: '',
      altText: 'Abstract orb illustration',
    },
  ],
};

function getAppConfig() {
  return appConfig;
}

export { getAppConfig };
