const appConfig = {
  categories: [
    {
      id: 'coding',
      label: 'Coding',
      iconKey: 'code',
      visualStyle: 'mint',
      order: 0,
      enabled: true,
    },
    {
      id: 'general',
      label: 'General',
      iconKey: 'sparkles',
      visualStyle: 'lavender',
      order: 1,
      enabled: true,
    },
    {
      id: 'writing',
      label: 'Writing',
      iconKey: 'edit',
      visualStyle: 'blush',
      order: 2,
      enabled: true,
    },
    {
      id: 'image-generation',
      label: 'Image',
      iconKey: 'image',
      visualStyle: 'lime',
      order: 3,
      enabled: true,
    },
    {
      id: 'business',
      label: 'Business',
      iconKey: 'briefcase',
      visualStyle: 'sky',
      order: 4,
      enabled: true,
    },
  ],
  tones: [
    {
      id: 'auto',
      label: 'Auto',
      iconKey: 'sparkles',
      premiumOnly: false,
      order: 0,
      promptPolicyKey: 'auto',
    },
    {
      id: 'professional',
      label: 'Professional',
      iconKey: 'briefcase',
      premiumOnly: true,
      order: 1,
      promptPolicyKey: 'professional',
    },
    {
      id: 'creative',
      label: 'Creative',
      iconKey: 'palette',
      premiumOnly: true,
      order: 2,
      promptPolicyKey: 'creative',
    },
    {
      id: 'casual',
      label: 'Casual',
      iconKey: 'chat',
      premiumOnly: true,
      order: 3,
      promptPolicyKey: 'casual',
    },
    {
      id: 'persuasive',
      label: 'Persuasive',
      iconKey: 'megaphone',
      premiumOnly: true,
      order: 4,
      promptPolicyKey: 'persuasive',
    },
    {
      id: 'technical',
      label: 'Technical',
      iconKey: 'settings',
      premiumOnly: true,
      order: 5,
      promptPolicyKey: 'technical',
    },
  ],
  templateCategories: [
    { id: 'coding', label: 'Coding', iconKey: 'code', order: 0 },
    { id: 'general', label: 'General', iconKey: 'sparkles', order: 1 },
    { id: 'writing', label: 'Writing', iconKey: 'edit', order: 2 },
    { id: 'image-generation', label: 'Image', iconKey: 'image', order: 3 },
    { id: 'business', label: 'Business', iconKey: 'briefcase', order: 4 },
  ],
  templates: [
    {
      id: 'coding-add-feature',
      categoryId: 'coding',
      title: 'Add a Feature',
      summary: 'Describe a new feature for an existing app or project.',
      promptBody: 'I want to add [feature] to my [framework] app',
      isQuick: true,
      enabled: true,
    },
    {
      id: 'coding-fix-bug',
      categoryId: 'coding',
      title: 'Fix a Bug',
      summary: 'Explain the bug, trigger, and current behavior.',
      promptBody: 'I have a bug where [problem] happens when [trigger]',
      isQuick: true,
      enabled: true,
    },
    {
      id: 'coding-build-screen',
      categoryId: 'coding',
      title: 'Build a Screen',
      summary: 'Outline a full screen with UI and behavior requirements.',
      promptBody: 'Build a [screen name] screen with [requirements]',
      isQuick: true,
      enabled: true,
    },
    {
      id: 'coding-refactor',
      categoryId: 'coding',
      title: 'Refactor Code',
      summary: 'Improve structure, readability, or maintainability.',
      promptBody: 'Refactor my [component] to [improvement goal]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'coding-auth',
      categoryId: 'coding',
      title: 'Add Authentication',
      summary: 'Set up sign-in and access control flows.',
      promptBody: 'Add [auth type] to my [framework] app',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'coding-api',
      categoryId: 'coding',
      title: 'Connect to API',
      summary: 'Integrate an external API into your app flow.',
      promptBody: 'Connect my app to [API] to [functionality]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'coding-database',
      categoryId: 'coding',
      title: 'Set Up Database',
      summary: 'Define storage, schema, and integration needs.',
      promptBody: 'Set up [database] for [use case] in my app',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'coding-debug',
      categoryId: 'coding',
      title: 'Debug an Error',
      summary: 'Investigate an error message with runtime context.',
      promptBody: 'I\'m getting [error] when [action happens]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'coding-performance',
      categoryId: 'coding',
      title: 'Improve Performance',
      summary: 'Optimize slow experiences or inefficient logic.',
      promptBody: 'My [feature] is slow, help me optimize it',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'coding-tests',
      categoryId: 'coding',
      title: 'Write Tests',
      summary: 'Generate tests with clear coverage goals.',
      promptBody: 'Write [test type] tests for [component]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'general-explain',
      categoryId: 'general',
      title: 'Explain a concept',
      summary: 'Turn a rough idea into a clear explanation.',
      promptBody: 'Explain [concept] in simple terms with examples and useful context.',
      isQuick: true,
      enabled: true,
    },
    {
      id: 'coding-review',
      categoryId: 'coding',
      title: 'Code review',
      summary: 'Review code for bugs, clarity, and performance.',
      promptBody: 'Review this code and suggest fixes, improvements, and edge cases...',
      isQuick: true,
      enabled: true,
    },
    {
      id: 'writing-blog-post',
      categoryId: 'writing',
      title: 'Blog Post',
      summary: 'Write a focused article for a specific audience.',
      promptBody: 'Write a blog post about [topic] for [audience]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'writing-social-caption',
      categoryId: 'writing',
      title: 'Social Caption',
      summary: 'Create platform-specific social copy with clear intent.',
      promptBody: 'Write a [platform] caption for [content] targeting [audience]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'writing-marketing-email',
      categoryId: 'writing',
      title: 'Marketing Email',
      summary: 'Draft conversion-focused email copy.',
      promptBody: 'Write a marketing email for [product] to [audience]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'writing-product-description',
      categoryId: 'writing',
      title: 'Product Description',
      summary: 'Highlight benefits with persuasive product copy.',
      promptBody: 'Write a product description for [product] highlighting [benefits]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'writing-email',
      categoryId: 'writing',
      title: 'Professional email',
      summary: 'Write a polished email with a clear tone and ask.',
      promptBody: 'Write a professional email about...',
      isQuick: true,
      enabled: true,
    },
    {
      id: 'image-realistic-photo',
      categoryId: 'image-generation',
      title: 'Realistic Photo',
      summary: 'Build a photorealistic scene with clear setting details.',
      promptBody: 'Create a photorealistic image of [subject] in [setting]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'image-digital-art',
      categoryId: 'image-generation',
      title: 'Digital Art',
      summary: 'Create stylized artwork with mood and style direction.',
      promptBody: 'Create digital art of [subject] in [style] with [mood]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'image-logo-design',
      categoryId: 'image-generation',
      title: 'Logo Design',
      summary: 'Describe a brand mark with strong aesthetic cues.',
      promptBody: 'Design a logo for [brand] that feels [adjectives]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'image-ui-screenshot',
      categoryId: 'image-generation',
      title: 'UI Screenshot',
      summary: 'Create a polished product mockup or interface concept.',
      promptBody: 'Create a UI mockup of [screen type] app with [style]',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'image-scene',
      categoryId: 'image-generation',
      title: 'Image prompt',
      summary: 'Describe style, camera, mood, and details clearly.',
      promptBody: 'Create a detailed image prompt for...',
      isQuick: false,
      enabled: true,
    },
    {
      id: 'business-plan',
      categoryId: 'business',
      title: 'Business plan',
      summary: 'Outline a plan with goals, positioning, and next steps.',
      promptBody: 'Create a business plan for...',
      isQuick: false,
      enabled: true,
    },
  ],
  homeFeatures: [
    {
      id: 'refine',
      title: 'Code with better prompts',
      subtitle: 'Turn rough coding tasks into production-ready AI instructions.',
      iconKey: 'sparkles',
      imageAssetKey: 'orb',
      actionType: 'compose',
      visualSize: 'large',
    },
    {
      id: 'voice',
      title: 'Use your voice',
      subtitle: 'Say what you mean naturally and edit it after.',
      iconKey: 'mic',
      imageAssetKey: 'voice',
      actionType: 'voice',
      visualSize: 'medium',
    },
    {
      id: 'templates',
      title: 'Browse templates',
      subtitle: 'Use starting points that already work well.',
      iconKey: 'grid',
      imageAssetKey: 'template',
      actionType: 'templates',
      visualSize: 'medium',
    },
  ],
  visualAssets: [
    {
      id: 'home-orb',
      placement: 'home-hero',
      lightAssetUrl: '',
      darkAssetUrl: '',
      altText: 'Abstract orb illustration',
    },
  ],
};

function getAppConfig() {
  return appConfig;
}

export { getAppConfig };
